/**
 * esbuild bundler for the Shouji Diannao Obsidian plugin.
 *
 * Modes (BUILD_MODE env var):
 *   - (default) : release build, minified, OBSYNC_DEV_BUILD=false
 *   - dev       : inline source maps, OBSYNC_DEV_BUILD=true
 *
 * Output: ./main.js  (load it together with manifest.json into
 *         <vault>/.obsidian/plugins/shoujidiannao/)
 */

import esbuild from 'esbuild';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const isDev = process.env.BUILD_MODE === 'dev';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Shouji Diannao — Obsidian 手机电脑同步插件
*/`;

/**
 * The sync core (crypto + protocol) lives in src/vendor/. It is referenced
 * by the bare specifiers `@obsync/crypto` / `@obsync/proto`; resolve those
 * to the vendored TypeScript source so the repo builds standalone.
 */
const obsyncVendorPlugin = {
  name: 'obsync-vendor',
  setup(build) {
    build.onResolve({ filter: /^@obsync\/(crypto|proto)$/ }, (args) => {
      const pkg = args.path.replace('@obsync/', 'obsync-');
      return { path: resolve(ROOT, 'src/vendor', pkg, 'index.ts') };
    });
  },
};

await esbuild.build({
  banner: { js: banner },
  entryPoints: [resolve(ROOT, 'main.ts')],
  bundle: true,
  format: 'cjs',
  platform: 'browser',
  target: 'es2021',
  outfile: resolve(ROOT, 'main.js'),
  sourcemap: isDev ? 'inline' : false,
  minify: !isDev,
  treeShaking: true,
  plugins: [obsyncVendorPlugin],
  external: [
    'obsidian',
    'electron',
    // Node built-ins — resolved by Obsidian desktop's Electron runtime.
    'node:crypto',
    'node:buffer',
    'node:util',
    'crypto',
    'buffer',
    'util',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
  ],
  define: {
    OBSYNC_DEV_BUILD: isDev ? 'true' : 'false',
    'process.env.NODE_ENV': JSON.stringify(isDev ? 'development' : 'production'),
  },
  logLevel: 'info',
});

console.log(`\nShouji Diannao bundled (${isDev ? 'dev' : 'release'}) → ${resolve(ROOT, 'main.js')}`);
